### ISSUE TITLE
Community Slack link is not working

### ISSUE THREAD

**Issue by maiqueb** [k8snetworkplumbingwg/community#20]
hey, the auto-invite link is not working, as reported in [this multus issue](https://github.com/k8snetworkplumbingwg/multus-cni/issues/1020#issuecomment-1521541274).

The error it throws is:
```
This link is no longer active
```

Could it be the generated link from #17 is short lived ?... Would we need some automation to generate new links periodically ?...

**Comment by maiqueb** [comment]
/cc @plwhite 
/cc @dougbtv 
/cc @s1061123 

Bringing this to your attention. 

Thanks for all the work you do for this community.

**Comment by plwhite** [comment]
Sorry - I tested that link, but it worked for me because I was already a member and failed to realise that would let it work! I just retested anonymously and the link does seem to have expired or to be invalid.

I don't have rights to generate a new link in the Slack workspace, but have asked for somebody to generate a link for me and will get back to you.

**Comment by plwhite** [comment]
I don't have rights, and am trying to get the self-invite link fixed (by asking people who do have rights). When I do, I will post here.

**Comment by dougbtv** [comment]
permanent invite link @maiqueb and @plwhite : 

https://join.slack.com/t/npwg-team/shared_invite/zt-1u2vmsn2b-tKdOokdPY73zn9B32JoAOg

**Comment by plwhite** [comment]
PR incoming with the README updated - @rsidhaarth see above
